### ISSUE TITLE
dynamically generate static visualizations from JASSS paper

### ISSUE THREAD

**Issue by alee** [comses/catalog#100]
http://jasss.soc.surrey.ac.uk/20/1/2.html

- interactive visualization that filters on `authors, platform, code, model documentation, sponsor, journal`
- frequency / frequency years
- code availability

To start with, create table

Indicator (Author, Platform, Code, etc.) | Number of publications | Code availability | (Other indicators aggregated / platform / sponsor / journal / keywords)
----- | ----- | ---- | ---- 
Marco A. Janssen | 12 | 90% | NSF (2) NIH (1) keywords
C. Michael Barton | 11 | 95% | NEH (3) keywords

network visualizations, eventually

**Comment by alee** [comment]
Hey @dhruvilpatel - feel free to comment on and add any additional notes that you took from our meeting today. This helps us to keep everything in context. Thanks!

**Comment by dhruvilpatel** [comment]
For Network Visualization :

	D3 JS 
		- Has good documentation to understand different functionalities
		- Requires no extra libraries
		
		Only supports 2D visualization

	D3 Force layout:
		- It provides good visualization by bringing up the nodes closer forcefully
		- Provides animated view for user to play with
		- Performs slow interaction with the user for large network graphs ( > 1000 nodes)
	
	D3 Static force layout using workerJS( Generates graph in the backend)
		- Performs faster once the graphs is generated due to static nature
		- It will be static. No animated interaction. Nodes position will be fixed But will be distributed widely amongst themselves taking up wide space.
		- Very bad visualization look
	
	D3 Force Simulation Using canvas (Faster for 1000 - 5000 nodes maybe more)
		- It also provide static kind of layout with little bit interactive but without animation thus providing better visualization that static force layout 
	
	https://github.com/anvaka/VivaGraphJS
	VivaGraphJS (Much faster for 10k-20k nodes - even more)
		- Uses WebGl (User graphics card must support WebGl)
		- Missing documentation. So don't know much options yet. But has few examples to work with
	
        https://github.com/anvaka/ngraph
	NGraph ( Provide 2d and 3d Visualization - faster for 200k Nodes and more)
		- Generates best UI for user experience
		- Work for offline graphs too
		- missing documentation of usage. 
		- Uses Webgl

**Comment by alee** [comment]
- http://sigmajs.org/
- https://plot.ly/javascript/
- http://visjs.org/

- https://stackoverflow.com/questions/19033151/javascript-library-for-dynamic-network-visualization

**Comment by alee** [comment]
add summary statistics

network visualization - do not display if too many nodes
identify a default view of the network

**Comment by alee** [comment]
mostly implemented, deferring to #132
