### ISSUE TITLE
automatically create "Source Code" model documentation linkages when code archive url is present

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/catalog#106]
It is not needed to have both a URL entry and "software" in model documentation. Perhaps only URL is sufficient and infer we have software in the model documentation.

**Comment by alee** [comment]
Agreed, source code as an entry in the Model Documentation set is definitely implied if the code archive URL is present (and reachable). 

@cpritcha we should add some logic to automatically add a relation between Publication and ModelDocumentation.SOURCE_CODE if the code archive URL is valid. Either as a periodic cron task or a signal to run on Publication.save etc.

**Comment by cpritcha** [comment]
Since we have code archive urls now we should remove "Source code" as a documentation category.

**Comment by cpritcha** [comment]
I've removed Source code as a documentation category
