### ISSUE TITLE
invalid URLs

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/catalog#107]
We need to keep track of URLs that are not functional or behind passwords. So far a note has been created if we came across this. It would be better to have a category "invalid URL" to keep track how frequent URLs do not work anymore.

**Comment by cpritcha** [comment]
URLStatusLog tracks this.

**Comment by MarcoAJanssen** [comment]
Please provide more information than a criptic response. I do not think it is resolved.

**Comment by cpritcha** [comment]
Dhruvil made a periodic validate urls task that goes through each publication and makes a request for each of the publication's urls. URLs responses are saved in the database. A `type` field tracks whether or not the request was successful (it also includes the url category such as whether or not it is a CoMSES url, a FigShare url etc).
