### ISSUE TITLE
connection with ASU library

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/catalog#116]
The two buttons that should pop up the links to the papers via the ASU library do not function properly since a week or two. I get the message Your search for TITLE AND (AuthorCombined: (AUTHOR NAMES)) returned 0 results
Maybe something is changed in the settings of the search in the ASU library.

**Comment by alee** [comment]
Looks like ASU library is now using a different search provider:

http://asu.summon.serialssolutions.com/search/results?q=<foo>

always returns nothing. The new URL appears to be

https://arizona-asu-primo.hosted.exlibrisgroup.com/primo-explore/search
