### ISSUE TITLE
build curator workflow for contacting authors

### ISSUE THREAD

**Issue by cpritcha** [comses/catalog#141]
This is an omnibus issue for the author contact curator workflow.

Add a curator workflow that enables a curator to contact authors of valid publications with missing or invalid code archive urls:

Tasks:

- [ ] first cut #147
- [ ] implement and test #71 
- [ ] select a set of publications, construct an email based on template(s) to send to the contact authors, reply-to: should be the curator sending the email
- [ ] keep track of emails sent
- [ ] aggregate emails to the same contact author so we don't spam them repeatedly with emails
- [ ] emails include links with unique edit URL to submit a code archive URL back for the given Publications

Some issues / corner cases:

- handle multiple code archive urls, some are valid, some are unreachable/invalid
- allow repeated edits
- edits should submit to a moderation queue, not update-in-place

**Comment by alee** [comment]
closing, remaining tasks are in #178
