### ISSUE TITLE
add some basic dashboard data

### ISSUE THREAD

**Issue by alee** [comses/catalog#15]
- list of N most recently edited items with links to the items
- N most recently author edited items, e.g., author updated codeurl
- Out of N publications in our catalog, M publications have a valid code URL. Provide link to the search filter that will pull up all of the publications missing a valid code URL.

**Comment by tgpatel** [comment]
Commit 9cd3714d3c07df70f827c9abcf79e968a0bd2427 adds recently edited items and recently authored edited items to dashborad

**Comment by tgpatel** [comment]
Commit 7bf3843c7d146ecf8ec9bc2488c403fc4e2537d9 adds data related to curator to the dashboard
