### ISSUE TITLE
URL categories

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/catalog#155]
The following categories are distinguished for the code URLs:
Comses
Open source 
Platform
Journal
Personal
Invalid
Others
Empty

As discussed on January 18, we should collect the data at a highest resolution, and have then a mapping system to aggregate the information. I would suggest to include the following categories:
Comses (Archive)
Zonodo (Archive)
Dataverse (Archive)
Figshare (Archive)
OSF (Archive)
Github (Repository)
SourceForge (Repository)
Bitbucket (Repository)
GoogleCode (Repository)
Journal
Dropbox (personal)
ResearchGate (personal)
Personal Webpage (personal)
Cormas (Platform)
NetLogo (Platform)
Journal
Invalid
Others
Empty

**Comment by cpritcha** [comment]
I think some "other" categories are needed such as:

Other (Archive)
Other (Repository)
Other (Personal)

Which can be divided at a later date (if an archive is only used once it may not deserve it's own category). 

There are also some government funded project websites like https://www.tellmeproject.eu/ which deserve a category. Maybe an

Organization Website 

category works for now.

**Comment by MarcoAJanssen** [comment]
I do not understand this. Why not one Other category, since this is only a category if it cannot be placed in anything else. (such as a new archive or new repository), If we experience this we may have to create 
a new archive or repository category.

Personal has many many forms, from a personal website, a project website, a department website, but they are all websites that will disappear within a few years. I don't want to get into all those different catergories of websites, so I just call it Personal website, eventhough it could be an organizational website. It does not matter for our purposes since they are all bad practices. Note that if we start having all kind of difficult borderline categories, it will be impossible for an undergraduate student to do this kind of work (and I do not want to keep doing this data entry for ever, so it should be transparent, and clear).

**Comment by cpritcha** [comment]
OK. I'll leave out other categories for repository, archive, platform etc. I think the "Personal" category should be named "Personal or Organizational" though. Any objections?

**Comment by MarcoAJanssen** [comment]
Sure "Personal or Organizational" is OK,
