### ISSUE TITLE
authors

### ISSUE THREAD

**Issue by MarcoAJanssen** [comses/catalog#160]
I had a look at the "Find Publications" and I noticed that again the list of authors are unreliable. Volker Grimm, the most prolific author, is not in the top 10, which suggest that there is something wrong again.

The "visualization" is still not working and extremely unclear what one needs to do. I click on various buttons and nothing happens. This has been a problem that I have mentioned for many months....

**Comment by cpritcha** [comment]
I never applied author deduplication to the catalog.comses.net, only catalog-dev.comses.net. It is fixed now. 

I've restarted the visualization. I've moved the visualization part of the issue to new issues,
