### ISSUE TITLE
create workflow between metadata curator & author

### ISSUE THREAD

**Issue by alee** [comses/catalog#2]
- candidate set of publications (pulled in via zotero import, harvested from other online aggregation feeds or direct sources, manual creation)
- partition publications into sets (status = complete, pending, new, ...)
- metadata curator selects publication, fills in some fields (at minimum verify contact author) and then clicks "preview/send email button" to send a templated email request to the author(s)

**Comment by tgpatel** [comment]
Commit 98a89eff3518e7f752799ffa8b6326fc01e134eb completes above listed tasks.
