### ISSUE TITLE
support citation graphs

### ISSUE THREAD

**Issue by alee** [comses/catalog#22]
- design a data model for a given publication's citations to create citation graphs
- consider graph database like neo4j or orientdb for the citation graph 
- get seed data from web of science results that marco downloads as an initial import, consider importing publication data directly from web of science (if possible)

**Comment by alee** [comment]
- should consider leveraging neo4j or orientdb instead of managing graphs in the RDBMS. Python REST support for neo4j has improved significantly, python-embedded no longer supported
- get seed data from web of science results that marco downloads as an initial import, may also want to import publication data directly from web of science results.

**Comment by alee** [comment]
Possible tools for parsing the incomplete and messy citation data:

- http://freecite.library.brown.edu/
- lookup via DOI if it exists

**Comment by cpritcha** [comment]
A small sample of some difficult to parse citations.

```
Lazega E, 2011, NEW DIR MOD ECON, P46.
Malarz K, 2011, J ARTIF SOC SOC SIMU, V14.
Will O, 2010, LECT NOTES ARTIF INT, V5683, P123.
Barton D., 2001, IMPACT OXWEEDING LAB.
Conservation International Climate Focus Terracarbon LLC StarVision Development and Policy Management Consultants, 2009, S AM REG INFR DEV FO.
Cummings A.R., 2013, THESIS.
FAO, 2008, UPD MIN DIET EN REQ.
Wilensky U, 1999, NETLOGO CTR CONNECTE.
R Development Core Team, 2011, R LANG ENV STAT COMP.
```

**Comment by alee** [comment]
A number of these we might be able to query if we search crossref.org by just Author and Year, and then do some fuzzy string matching between the journals

**Comment by cpritcha** [comment]
Keep using Postgres and python networkx for now
