### ISSUE TITLE
proper mail setup from docker containers

### ISSUE THREAD

**Issue by alee** [comses/catalog#71]
outbound emails from the container don't work yet, need to configure & test a similar sparkpost setup as we are using for comses.net

**Comment by alee** [comment]
outbound emails are now working on dev, still need to repeat the same process on prod:

- update config.ini with correct sparkpost credentials
- rebuild + redeploy docker containers

**Comment by cpritcha** [comment]
I added the necessary setup to the `config.ini` file. You can now send emails.
